# Generated by Django 4.0.5 on 2022-09-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_safe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saved_info',
            new_name='Profile_info',
        ),
    ]
