# Generated by Django 4.0.5 on 2022-09-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_safe', '0003_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
