# Generated by Django 4.0.5 on 2022-10-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_safe', '0005_user_name_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
