# Generated by Django 4.0.5 on 2022-10-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_safe', '0006_user_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Saved_info',
        ),
    ]
