# Generated by Django 4.0.5 on 2022-10-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password_safe', '0007_rename_user_saved_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_info',
            name='key',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
